//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcac.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsiscomexweb_robo
    {
        public int nr_sequencia { get; set; }
        public int nr_processo { get; set; }
        public Nullable<int> nr_registro_di { get; set; }
        public Nullable<int> nr_seq { get; set; }
        public string tp_consulta { get; set; }
        public string tp_acao { get; set; }
        public Nullable<System.DateTime> dt_agendamento { get; set; }
        public Nullable<System.DateTime> dt_realizacao { get; set; }
        public Nullable<System.DateTime> dt_registro_di { get; set; }
        public int nr_tentativas { get; set; }
        public string tx_erro { get; set; }
        public Nullable<int> cd_usuario { get; set; }
        public string cpf_certificado { get; set; }
        public int in_rodando { get; set; }
        public Nullable<int> in_desembaraco { get; set; }
        public string tp_anuencia { get; set; }
        public Nullable<int> in_situacao { get; set; }
        public string xml_comando { get; set; }
        public string xml_retorno { get; set; }
        public byte[] pdf_extrato { get; set; }
        public byte[] pdf_comprovante { get; set; }
    }
}
